### ISSUE TITLE
[Plan] Submission to F-Droid 

### ISSUE THREAD

**Issue by chr56** [chr56/Phonograph_Plus#64]
Phonograph Plus has been on [LzzyOnDroid](https://apt.izzysoft.de/fdroid/index/apk/player.phonograph.plus) already, and I am planning making it on official F-Droid Repo.

- [x] Release v0.6.0 first.

- [x] Update `fastlane/metadata/android` automatically.

  [`ReleaseNote.md`](https://github.com/chr56/Phonograph_Plus/blob/preview_0.6.0-dev2/ReleaseNote.md) is the _source_ of new changelog.
  `ReleaseNote.md` is parsed by [`tools/changelog-generator`](https://github.com/chr56/Phonograph_Plus/tree/preview_0.6.0-dev2/tools/changelog-generator). Then it generates [`GitHubReleaseNote.md`](https://github.com/chr56/Phonograph_Plus/blob/preview_0.6.0-dev2/GitHubReleaseNote.md) for Github Release (automatically creating Release after pushing tags via Github Action), and generates HTML version of changelogs in app/src/main/[`assets`](https://github.com/chr56/Phonograph_Plus/tree/preview_0.6.0-dev2/app/src/main/assets), and encodes to URL for uploading to Telegram.
  So **just modify changelog-generator** to generate changelogs to `fastlane/metadata/android`.
- [x] Make sure f-droid can `AutoUpdate`d.

  <del>[`version_catalog`](https://github.com/chr56/Phonograph_Plus/blob/preview_0.6.0-dev2/version_catalog.json) is the current _source_ for in-app version check.
  Just adding new properties for f-droid's `UpdateCheckData` is fine (or creating a new file) to ensure totally manual control the version check.</del>
  `./fdroid.properties` is created for fdroid checking updates.

- [x] Write a f-droid `<package-name>.yml`.

  Just find an another very detailed app as template to copy & modify. 
  And ensure `flavours`([`stable`](https://github.com/chr56/Phonograph_Plus/blob/preview_0.6.0-dev2/app/build.gradle.kts#L87)), `subdir`(`app/`), proper `AutoUpdateMode` (as well as `UpdateCheckMode` & `UpdateCheckData`)

- [x] clone & add & make MR

- [x] fix & wait for maintainers's response.

**Comment by chr56** [comment]
draft `<package-name>.yml`:

```
Categories:
  - Multimedia
License: GPL-3.0-only
AuthorName: chr_56
SourceCode: https://github.com/chr56/Phonograph_Plus
IssueTracker: https://github.com/chr56/Phonograph_Plus/issues
Translation: https://crowdin.com/project/phonograph-plus
Changelog: https://phonographplus.github.io/changelogs/changeslogs/changelog.html

RepoType: git
Repo: https://github.com/chr56/Phonograph_Plus

AutoName: Phonograph Plus

Builds:
  - versionName: 0.6.0
    versionCode: 500
    commit: v0.6.0
    subdir: app
    gradle:
      - stable

AutoUpdateMode: Version
UpdateCheckMode: Tags ^v(.*)$
UpdateCheckData: fdroid.properties|latest_version_code=(\d+)|fdroid.properties|latest_version_name=(.*)
CurrentVersion: 0.6.0
CurrentVersionCode: 500
```
